### ISSUE TITLE
Issues with Building Apps and Docker Images

### ISSUE THREAD

**Issue by faromero** [uwsampl/nexus#18]
Hello,
I am interested in trying out Nexus. After following your [Installation](https://github.com/uwsampl/nexus/blob/master/INSTALL.md) instructions, I was successfully able to build Nexus, but have been unable to (1) run the [Local Tests without Docker](https://github.com/uwsampl/nexus#local-tests-without-docker), or (2) [Build Docker Image](https://github.com/uwsampl/nexus#build-docker-image). For (1), I am unable to build the simple_app (or any app) because _libnexus_ is not being built according to the installation instructions, and so far, I have been unable to successfully build it through modifications to the root's CMakeLists.txt or the app's Makefile. For (2), the base image builds, but the other three do not for various reasons:  _NexusBackendDockerfile_ fails on making backend and tools, seemingly because of caffe2 (which I attempted to disable by having it not compile that backends, but this was unsuccessful), while _NexusSchedulerDockerfile_ and _NexusAppLibDockerfile_ seem to have variable scope and type errors.

Any guidance for how to get it working would be greatly appreciated. Thank you in advance!

**Comment by abcdabcd987** [comment]
Thanks for giving Nexus a try :) I'm aware that the instructions and some files are not up-to-date. I happen to be working on reorganizing Nexus files and build system this week. I'll let you know when it's ready.

**Comment by faromero** [comment]
Thank you, looking forward to the updates!

**Comment by abcdabcd987** [comment]
Updated. I'm closing this issue. Feel free to reopen if you have more questions.
