### ISSUE TITLE
frontend and scheduler error

### ISSUE THREAD

**Issue by Told** [uwsampl/nexus#19]
Hi，abcdabcd987！
I follow the steps from https://github.com/uwsampl/nexus/blob/master/examples/README.md. Then I got frontend and scheduler error. 
frontend error log: Load model error: NOT_ENOUGH_BACKENDS
![frontend-error](https://user-images.githubusercontent.com/1896984/83615695-7c3b1100-a5b9-11ea-89f1-962672c00f63.jpeg)
scheduler error log:  failed to connect to all addresses
![scheduler-error](https://user-images.githubusercontent.com/1896984/83616009-e05dd500-a5b9-11ea-915f-c0b14eaef683.jpeg)

backend runs normal
![backend-log](https://user-images.githubusercontent.com/1896984/83616229-29158e00-a5ba-11ea-930e-d173e863b169.jpeg)

what did I do wrong?

**Comment by abcdabcd987** [comment]
Thanks for giving Nexus a try!

From the screenshot, I found a few possible reasons why this happens:

1. Did you start the frontend before the backends? Frontends need to be started after backends are ready, otherwise it'll complain about not enough backends.
2. The scheduler log shows that it can't find the profile. Have you profiled the model on the GPU? If you did profile, try `ls $MODEL_DIR/profiles/` and see if the profile is actually inside the directory or subdirectories. Also a reminder that the profile is per GPU card, not per GPU kind. I see you have two GPUs, perhaps you just profiled one?

**Comment by Told** [comment]
> Thanks for giving Nexus a try!
> 
> From the screenshot, I found a few possible reasons why this happens:
> 
> 1. Did you start the frontend before the backends? Frontends need to be started after backends are ready, otherwise it'll complain about not enough backends.
> 2. The scheduler log shows that it can't find the profile. Have you profiled the model on the GPU? If you did profile, try `ls $MODEL_DIR/profiles/` and see if the profile is actually inside the directory or subdirectories. Also a reminder that the profile is per GPU card, not per GPU kind. I see you have two GPUs, perhaps you just profiled one?

hi @abcdabcd987 ,  as you said,  I deployed Nexus again. 
First, I started two profiler process on GPU 0 and 1, ls s $MODEL_DIR/profiles/ likes:
![profiler](https://user-images.githubusercontent.com/1896984/83865248-86474600-a758-11ea-962a-91d74795d034.jpeg)
 then  I also deployed two backend process on GPU0 and GPU 1, and they had already registered to the scheduler:
![backend-0](https://user-images.githubusercontent.com/1896984/83865453-c9091e00-a758-11ea-9dd2-d1c102b40a2a.jpeg)
![backend-1](https://user-images.githubusercontent.com/1896984/83865539-e50cbf80-a758-11ea-8eaf-02212bb42583.jpeg)
![scheduler-reg](https://user-images.githubusercontent.com/1896984/83865711-2c934b80-a759-11ea-9e97-69d93ffa61cc.jpeg)
But, finally I started frontend process, I still got the same error said NOT_ENOUGH_BACKENDS.：
![frontend-error-1](https://user-images.githubusercontent.com/1896984/83865876-72e8aa80-a759-11ea-899a-66237e46504e.jpeg)

**Comment by abcdabcd987** [comment]
I just realized that the instruction [here](https://github.com/uwsampl/nexus/blob/master/examples/README.md) is slightly outdated. You would also need to specify the image width and height when starting the front end. Like:

```
docker run -it --rm --gpus all --network=nexus-net --name=nexus-simple-frontend -p=9001 -p=9002 abcdabcd987/nexus \
    /nexus/build/simple -framework=tensorflow -model=resnet_0 -latency=50 -width=224 -height=224 -alsologtostderr -colorlogtostderr \
                        -sch_addr=nexus-scheduler:10001
```

**Comment by Told** [comment]
> I just realized that the instruction [here](https://github.com/uwsampl/nexus/blob/master/examples/README.md) is slightly outdated. You would also need to specify the image width and height when starting the front end. Like:
> 
> ```
> docker run -it --rm --gpus all --network=nexus-net --name=nexus-simple-frontend -p=9001 -p=9002 abcdabcd987/nexus \
>     /nexus/build/simple -framework=tensorflow -model=resnet_0 -latency=50 -width=224 -height=224 -alsologtostderr -colorlogtostderr \
>                         -sch_addr=nexus-scheduler:10001
> ```

IT WORKS! Thanks. please update the example readme.
